#!/bin/sh

case $# in
    1)
	if [ -r $DATA/$NEW_DB ]; then
	    $BIN/netmux -d$DATA/$GDBM_DB -i$DATA/$NEW_DB -o$1 -u
	elif [ -r $DATA/$INPUT_DB ]; then
	    echo "No recent checkpoint db. Using older db."
	    $BIN/netmux -d$DATA/$GDBM_DB -i$DATA/$INPUT_DB -o$1 -u
	elif [ -r $DATA/$SAVE_DB ]; then
	    echo "No input db. Using backup db."
	    $BIN/netmux -d$DATA/$GDBM_DB -i$DATA/$SAVE_DB -o$1 -u
	else
	    echo "No dbs. db unload failed."
	    exit 1
	fi
	;;
    *) echo use as db_unload mygame.flat; exit 1 ;;
esac
